### ISSUE TITLE
Example command under 'Proxies' is incorrect

### ISSUE THREAD

**Issue by rmt-hpe** [HP-Haven-OnDemand/havenondemand-python#2]
client = IODClient("http://api.idolondemand.com/", "myapikey",proxies=proxyDict)

Keyword should be ‘proxy’ not ‘proxies’. Or possibly worth updating the code instead for consistency with requests.

http://iod-python.readthedocs.org/en/latest/

**Comment by tylernappy** [comment]
Updated README to reflect correction. Also, the URL provided is outdated documentation and naming conventions. Please use the README.md in this repo as the official up to date documentation for the wrapper.
