### ISSUE TITLE
Examples should be updated to use http://api.havenondemand.com

### ISSUE THREAD

**Issue by rmt-hpe** [HP-Haven-OnDemand/havenondemand-python#5]
At some point http://api.idolondemand.com should be updated to http://api.havenondemand.com as the former won't be around indefinitely.

http://iod-python.readthedocs.org/en/latest/

**Comment by tylernappy** [comment]
Hi,

The URL you provided is outdated documentation and naming conventions. For the most recent document, please refer to the README.md file in this repo.
